services:
  frontend:
    image: ghcr.io/use-tusk/tusk-frontend:latest

  https-portal:
    image: steveltn/https-portal:1
    env_file: .env
    environment:
      DOMAINS: >
        ${DOMAIN} -> http://frontend:1234,
        ${DOMAIN}:8000 -> http://backend:8000,
      CLIENT_MAX_BODY_SIZE: 40M
      KEEPALIVE_TIMEOUT: 605
      PROXY_CONNECT_TIMEOUT: 600
      PROXY_SEND_TIMEOUT: 600
      PROXY_READ_TIMEOUT: 600
      SERVER_NAMES_HASH_BUCKET_SIZE: 64
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    restart: always

  backend:
    image: ghcr.io/use-tusk/tusk-backend:latest
    env_file: .env
    depends_on: &backend_depends_on
      postgres:
        condition: service_healthy

  default:
    image: ghcr.io/use-tusk/tusk-backend:latest
    env_file: .env
    depends_on: *backend_depends_on
    environment:
      - GAE_SERVICE=default

  runs:
    image: ghcr.io/use-tusk/tusk-backend:latest
    env_file: .env
    depends_on: *backend_depends_on
    environment:
      - GAE_SERVICE=runs

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tusk
      PGPORT: 5433
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-d", "tusk"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db:
    driver: local

networks: 
  default:
    driver: bridge

