services:
  frontend:
    image: ghcr.io/use-tusk/tusk-frontend:latest
    ports:
      - "1234:80"

  backend:
    image: ghcr.io/use-tusk/tusk-backend:latest
    env_file: .env
    depends_on: &backend_depends_on
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

  default:
    image: ghcr.io/use-tusk/tusk-backend:latest
    env_file: .env
    depends_on: *backend_depends_on
    environment:
      - GAE_SERVICE=default

  runs:
    image: ghcr.io/use-tusk/tusk-backend:latest
    env_file: ./env
    depends_on: *backend_depends_on
    environment:
      - GAE_SERVICE=runs

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tusk
      PGPORT: 5433
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-d", "tusk"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db:
    driver: local

networks: 
  default:
    driver: bridge

